---
name: Longer Tweet comment
about: "Don't use this directly. This template is used for comments on longer tweets. Links to prefilled issue templates are provided at the bottom of each longer tweet."
labels: comment
---

<!-- Add your comment here -->
