name: Comment on longer tweet
on:
  issues:
    types: opened
# Avoid "Context access might be invalid"
# https://github.com/github/vscode-github-actions/issues/67#issuecomment-1646017038
env:
  MESSAGE:
permissions:
  contents: write
  issues: write
jobs:
  comment:
    name: Write comment to comments.yml
    # https://docs.github.com/en/actions/learn-github-actions/expressions#example-using-an-object-filter
    if: ${{ contains(github.event.issue.labels.*.name, 'comment') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Write to _data/comments.yml
        run: |
          npm install
          # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-of-a-multiline-string
          {
            echo 'MESSAGE<<EOF'
            node _data/add-comment.js '${{ toJson(github.event) }}'
            echo EOF
          } >> "$GITHUB_ENV"
      - name: Push changes
        run: |
          # https://stackoverflow.com/a/25149786
          if [[ `git status --porcelain` ]]; then
            git config --local user.name 'Github Actions: ${{ github.action }} (for @${{ github.event.sender.login }})'
            git config --local user.email '${{ github.event.sender.login }}@users.noreply.github.com'
            git add _data/comments.yml
            git commit -m "Add comment from @${{ github.event.sender.login }}

          Resolves #${{ github.event.issue.number }}"
            git push
          else
            gh issue close ${{ github.event.issue.number }} --reason 'not planned'
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Comment on the issue if needed
        run: |
          gh issue comment ${{ github.event.issue.number }} --body "$MESSAGE"
        if: ${{ env.MESSAGE != '' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
